### ISSUE TITLE
Idea/Funcionalidad: en la modalidad "Word use" se presenta una única palabra, "bebé"

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#11]
La modalidad "Word use" solo me ofrece la palabra bebé:

![image](https://cloud.githubusercontent.com/assets/16288726/16200197/9acaf66e-370c-11e6-8edf-9a6e0a559fdf.png)

**Comment by jgsogo** [comment]
Por lo que veo tu informante está localizado en "España", por lo que _a priori_ sólo puede responder sobre palabras-significados que no pertenezcan a su zona (y únicamente está incluída la palabra "bebé" fuera de España). Cambia tu zona a cualquier lugar que no sea "España" para que te aparezcan el resto.

-----
De aquí se deriva una pregunta importante (a tratar, si lo consideráis oportuno en otro issue):
 1. ¿Sólo queremos mostrar palabras de fuera de la región del informante o queremos mostrarle todas? En cierto modo, mostrar palabras también de la región sirve para validar los datos aportados por otros informantes (éste caso es paradigmático: hubieras respondido "do not recognize..." y la valoración del informante que aportó esta palabra se resentiría)
