### ISSUE TITLE
"Word alternate": mostrará únicamente las palabras que algún informante en tu región ha dicho que no conoce

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#12]
Si en el juego Word use un informante no ha pulsado nunca los botones "yo no la uso pero la he oído o leído algunas veces" o "No la uso ni la había oído o leído antes" no necesitamos solicitarle palabras alternativas, por lo que el juego "Word alternate" no debería estar disponible.
Cuando este juego esté disponible sería bueno que un icono le haga saber al informante que tiene palabras nuevas allí.

**Comment by jgsogo** [comment]
Quiero más opiniones sobre esto. De esa forma limitaríamos la interfaz **WordAlternate** únicamente a aquellas palabras sobre las que el informante ya ha dicho que "no reconoce"... me gustaría tener más opiniones a favor y en contra sobre este punto.

**Comment by mariavarelar** [comment]
Pensé que habíamos llegado a un acuerdo sobre este aspecto. En el mail de los días 9-10 de junio que tiene por asunto Re: [Neutrón] Revisión de la reunión de seguimiento - Juego 2 parecía que habíamos optado por este camino, ¿no?

**Comment by jgsogo** [comment]
He cambiado el título a algo más evidente y que resume lo que hay que hacer aquí. Encolo la tarea ^^
