### ISSUE TITLE
Idea/Funcionalidad: cruce de lemas y acepciones II

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#13]
La acepción que se mostraba en el juego Word use para "bebé" ("que empieza a aparecer") no se recoge en Consulta:

![image](https://cloud.githubusercontent.com/assets/16288726/16200744/ce02ba56-370e-11e6-8426-f1eefe976b2a.png)

Aunque es lógico que sea así, puede parecer una incoherencia a ojos de los informantes. Este me parece otro argumento a favor de evitar los cruces entre lemas y acepciones.

**Comment by jgsogo** [comment]
No se recoge porque es un par palabra-definición aportado por un informante jgsogo[Bolivia] que no es "searchable" (ver modelo *Informers* en la interfaz de administración).

¿Lo consideramos un bug o comportamiento deseado? Es decir, si aceptamos la validación cruzada entre informantes (tú estás validando las palabras aportadas por otro), tenemos que aceptar que en la búsqueda algunas palabras no salgan hasta que hayan sido validadas, ¿no?

**Comment by mariavarelar** [comment]
Sin duda. No había detectado que era una palabra aportada por un informante. Todo claro ahora.
Como dices, en la búsqueda solo deben mostrarse palabras validadas. Ahora, ¿cómo de validadas deben estar?

**Comment by jgsogo** [comment]
Cierro y abro #17 con este tema.
