### ISSUE TITLE
Usabilidad: combos en el registro de informantes

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#14]
¿Podemos utilizar combos para recoger la información relativa al nivel de estudios y a cómo nos han conocido los informantes?
Nivel de estudios: ed. básica, ed. secundaria, ed. universitaria
Cómo nos han conocido: Cálamo&Cran, Fundéu, Universidad, otros
![image](https://cloud.githubusercontent.com/assets/16288726/16452914/1c908ee8-3e0b-11e6-9973-11d89642c0b4.png)
Por otra parte, todos los datos que solicitamos son obligatorios, podemos eliminar los asteriscos.

**Comment by jgsogo** [comment]
:+1:
