### ISSUE TITLE
Idea/Funcionalidad: realizar cambios en el perfil de usuario

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#15]
Que el informante realice cambios en el perfil personal (nombre, apellido, e-mail) no parece un problema. Que realice cambios que afecten a su nacionalidad o nivel de estudios cuando ya ha informado sobre alguna palabra sí es un inconveniente.

¿Podemos hacer esto?

**Usuarios que todavía no han contribuido:** esta pantalla sí les permitirá realizar modificaciones (pero unifiquemos con la pantalla de registro: mismos títulos para los campos y combo para el nivel de estudios).

![image](https://cloud.githubusercontent.com/assets/16288726/16453359/ded1e802-3e0c-11e6-8d25-de29c5dbf650.png)

**Usuarios que ya hayan contribuido:** tendrán que ponerse en contacto con nosotros y explicarnos a qué se debe el cambio.  Para ellos, esta pantalla será solo informativa.

![image](https://cloud.githubusercontent.com/assets/16288726/16453596/a9142634-3e0d-11e6-97cb-98db79d3e3b6.png)

**Comment by jgsogo** [comment]
I like it :+1: Me encargo.
