### ISSUE TITLE
Texto: pantalla Únete

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#16]
Correcciones pendientes en el texto de esta pantalla:

1. Actualizar la sección “¿qué tendría que hacer?” al sistema de tres juegos.
2. Restringir el uso del verbo “participar” a la pantalla “Participa”. Aquí utilizaremos “unirse” o “formar parte”.

Otros:
Los hipervínculos no se pueden activar todavía, pero no nos olvidemos de ellos.

![image](https://cloud.githubusercontent.com/assets/16288726/16454244/39e92f68-3e10-11e6-9a0e-a3fc47247374.png)

**Comment by jgsogo** [comment]
Lo puedes modificar tú misma, y sin salir de github :dancer: Esos textos los tienes aquí, prueba, y si tienes algún problema, te echo una mano:

https://github.com/jgsogo/neutron/blob/master/webapp/server/templates/join.html

**Comment by mariavarelar** [comment]
¡Genial! Avísame si he roto algo ;-)
