### ISSUE TITLE
Validación de palabras aportadas por un informante

### ISSUE THREAD

**Issue by jgsogo** [jgsogo/neutron#17]
En #13 ha salido el problema sobre cuándo dar por validada una palabra aportada por un informante... ¿ideas?

Los datos que tenemos son las opiniones vertidas por otros informantes sobre esa misma palabra, es decir, el grado de aceptación del par palabra-significado aportado por informantes que sean de su misma región (entiendo que desacharíamos las opiniones de los informantes de otras regiones).

**Comment by mariavarelar** [comment]
(Leer primero #10)

La alternativa ofrecida por un informante sería válida si:

- No es la primera vez que un informante ofrece esa alternativa para la acepción dada.
- Después de incorporarla al glosario, otros informantes indican que la utilizan para la acepción dada.

No es necesario que la aceptación de la nueva palabra venga de informantes de la misma región. Si un hablante argentino, uno colombiano y uno peruano nos sugieren una palabra, tenemos que seguir estudiándola, puede ser un caso de español neutro muy interesante.

**Comment by jgsogo** [comment]
Creo que con lo comentado en #10 relativo a los supervisores será suficiente para este issue.

Respecto a lo otro que se menciona aquí: informantes de geografías diferentes indican que utilizan una misma palabra para una acepción, creo que es algo que debería identificarse del análisis de los datos. Si os parece lo apuntamos, pero _a priori_ no es algo que se nos vaya a olvidar, ¿no?

**Comment by jgsogo** [comment]
Lo cierro, entiendo que análisis de datos es algo que habrá que ver con detalle en el futuro.
