### ISSUE TITLE
Idea/Funcionalidad: en "Coarse" no necesitamos repetir lemas

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#18]
En el juego “coarse” no necesitamos que un lema se presente tantas veces como acepciones suyas recoge el diccionario. Una aparición por lema es suficiente. Menos trabajo para los informantes ;-)

**Comment by jgsogo** [comment]
Lo marco como inválido porque esto no debería estar ocurriendo en ningún caso (salvo que se te acabe la lista de palabras).

¿Puedes confirmarlo?

**Comment by jgsogo** [comment]
A mí no me ocurre... a través de la interfaz de administración puedes llegar hasta los informantes y en la vista de detalle ver las palabras que se les van a mostrar (y el orden); copio captura:

![image](https://cloud.githubusercontent.com/assets/1406456/16901811/ed422416-4c4d-11e6-8fc5-144e574c7cc6.png)

**Comment by mariavarelar** [comment]
En la lista que copias aparece dos veces zoológico. ¿Se puede hacer una limpieza automática de estos casos? Suena a pesadilla, pero tengo que intentarlo ;-)

**Comment by jgsogo** [comment]
Aparece:
 1. zoológico, ca
 2. zoológico

...y son dos entradas distintas del diccionario. Que no es el caso en el que se tiene la misma entrada varias veces porque existen diferentes acepciones. Aquí entra el tema que comentamos de ¿cómo tratar esos masculino/femenino? Si la entrada primera hubiera sido sólo "zoológico" entonces no se produciría esta repetición.

**Comment by mariavarelar** [comment]
Sí, sí, por eso te pregunto si es posible hacer una limpieza automática de esos casos. Yo podría hacerla con una macro (y Antonio mejor que yo y más rápido), y darte un listado limpio, pero algo me dice que no queremos salir a Word o a Excel para crear una lista nueva solo para el juego grosero/no grosero. ¿O sí?

**Comment by jgsogo** [comment]
No queremos, no.

Tenemos que ver la casuística y se programa algo. Básciamente es el mismo código que tendría esa macro. ¿Valdría algo como quedarse con lo que hay antes de la "coma" y si coincide con otro no mostrarlo? ¿O hay algún caso raruno donde querríamos componer la palabra en femenino para ver si ésa sí es malsonante?

**Comment by jgsogo** [comment]
_Nota.-_ Actualmente tenemos 4105 palabras que contienen ese "masculino, femenino"...

**Comment by mariavarelar** [comment]
Quedarnos con lo que hay antes de la coma y ver si hay coincidencias puede valer, suena muy bien. El caso de los femeninos no debería ser un problema porque ese es el tipo de grosería que no nos hemos propuesto identificar, la que depende del contexto o el tono.

**Comment by jgsogo** [comment]
Yo creo que hay palabras que sí son groseras con un género y no con el otro, se me ocurre "pollo/polla", pero estoy convencido de que a lo largo y ancho de la hispanidad hay otros muchos ejemplos..

**Comment by mariavarelar** [comment]
Ok, este ejemplo no es como el de zorro, rra, es un pequeño fastidio.
Pongamos que no eliminamos la entrada pollo, lla del juego coarse, ¿qué hace el informante cuando se la encuentre? ¿Es o no es malsonante? Unos se centrarán en el masculino, otros en el femenino y a los demás les estallará la cabeza :D.
Si aceptamos que los informantes no leerían unas instrucciones que les ayuden a responder con cierta seguridad, lo único que nos queda es desdoblar la entrada (presentar por separado el masculino y el femenino), si no la desdoblamos, la respuesta no tendrá mucho valor.
En todo caso, ocurre algo similar con el juego uso/no uso. Por ejemplo, yo no uso "pizpireto", en masculino, ni "polizona", en femenino, y esta podría ser una información interesante que nos vamos a perder.
Así que... ¿qué es razonable hacer? Desdoblar las entradas supone hacerle 4105 preguntas más en los juegos coarse y uso/no uso a cada informante y puedo imaginar que será un reto desde el punto de vista técnico.
¿Hacemos la vista gorda? ¿Confiamos en que los informantes sí lean las instrucciones con respecto al género?

**Comment by jgsogo** [comment]
Yo desdoblaría en "coarse", pero no en "uso/no uso". De alguna manera en
"coarse" queremos que el informante responda un poco por impulso, mientras
que el "uso/no uso" es un poco más reflexivo, ¿no?

**Comment by jgsogo** [comment]
Además, el "uso/no uso" va acompañado de ejemplos y estoy convencido de que los ejemplos van a utilizar la forma común en vez de la rara.

**Comment by mariavarelar** [comment]
Me parece bien, además en uso/no uso íbamos a tener demasiadas combinaciones entrada-acepción no válidas. Vamos con los dos géneros en coarse :)
¡Al ataque!

**Comment by jgsogo** [comment]
Quedo a la espera del ok del mail que te he enviado :wink:

**Comment by mariavarelar** [comment]
Visto el listado, estas son las erratas que hay que corregir:

sacristána
saltarína
sirvientta
danzarína
disa
bailarína
benjamína
gigantta
gobernantta
guardiána
jeffa
infantta
alazána
alcahuetta
alemána
andarína
elefantta
regordetta
parlanchína
presidentta
presurora
nenna
vicepresidentta
malandrína
mallorquína
mastína
menorquína
musulmána
haragána
holgazána
caciquca
cantarína
capitána
catalána
charlatána
clientta
comediantta
talibána
tunantta

Por otra parte, aunque no los he ido buscando de forma rigurosa, he visto varios casos de doble grafía para los que no es necesario que conservemos las dos posibilidades (eso sí, para "México" siempre siempre siempre con x):

sabihondo, da ==>
sabiondo, da ==>
sicológico, ca ==>
sicólogo, ga ==>
sicotécnico, ca ==>
siquiátrico, ca ==>
síquico, ca ==>
fláccido, da ==>
flácido, da ==>
ambidextro, tra ==>
ambidiestro, tra ==>
antiinflamatorio, ria ==>
antinflamatorio, ria ==>
pasterizado, da ==>
pasteurizado, da ==>
posoperatorio, ria ==>
postoperatorio, ria ==>
psicológico, ca ==>
psicólogo, ga ==>
psicotécnico, ca ==>
psiquiátrico, ca ==>
psíquico, ca ==>
yugoeslavo, va ==>
yugoslavo, va ==>
mejicano, na ==>
mexicano, na ==>
transcrito, ta ==>
transgresor, ra ==>
translúcido, da ==>
transpuesto, ta ==>
trascrito, ta ==>
trasgresor, ra ==>
traslúcido, da ==>
traspuesto, ta ==>

Por último, he ido marcando palabras que yo no mostraría a los informantes, para que vayamos teniendo una idea del porcentaje que se va a quedar por el camino. Serían:

zamorano, na ==>
zaragozano, na ==>
salmantino, na ==>
santacrucero, ra ==>
santanderino, na ==>
segoviano, na ==>
segundo, da ==>
seiscientos, tas ==>
séptimo, ma ==>
septuagésimo, ma ==>
setecientos, tas ==>
sexagésimo, ma ==>
sexto, ta ==>
décimo, ma ==>
decimoctavo, va ==>
decimocuarto, ta ==>
decimonoveno, na ==>
decimoprimero, ra ==>
decimoquinto, ta ==>
decimosegundo, da ==>
decimoséptimo, ma ==>
decimosexto, ta ==>
decimotercero, ra ==>
diecinueveavo, va ==>
dieciochavo, va ==>
dieciochoavo, va ==>
dieciseisavo, va ==>
diecisieteavo, va ==>
diezmilésimo, ma ==>
doceavo, va ==>
doscientos, tas ==>
duodécimo, ma ==>
burgalés, sa ==>
formenterano, na ==>
gaditano, na ==>
granadino, na ==>
grancanario, ria ==>
guadalajareño, ña ==>
guipuzcoano, na ==>
alavés, sa ==>
albaceteño, ña ==>
alicantino, na ==>
aragonés, sa ==>
ochocientos, tas ==>
octavo, va ==>
onceavo, va ==>
orensano, na ==>
otro, tra ==>
el, la ==>
él, ella ==>
ellos, ellas ==>
enésimo, ma ==>
ese, esa ==>
este, esta ==>
riojano, na ==>
quien más, quien menos ==>
quinceavo, va ==>
quincuagésimo, ma ==>
quinientos, tas ==>
quinto, ta ==>
quiteño, ña ==>
palentino, na ==>
pamplonés, sa ==>
pontevedrés, sa ==>
navarro, rra ==>
ninguno, na ==>
nosotros, tras ==>
novecientos, tas ==>
noveno, na ==>
noventavo, va ==>
nuestro, tra ==>
numantino, na ==>
valenciano, na ==>
vallisoletano, na ==>
veinteavo, va ==>
veintiuno, na ==>
vigésimo, ma ==>
vitoriano, na ==>
vizcaíno, na ==>
vosotros, tras ==>
vuestro, tra ==>
malagueño, ña ==>
mallorquín, na ==>
maño, ña ==>
milésimo, ma ==>
millonésimo, ma ==>
murciano, na ==>
leonés, sa ==>
leridano, na ==>
lo, la ==>
logroñés, sa ==>
un, una ==>
undécimo, ma ==>
uno, una ==>
catorceavo, va ==>
centésimo, ma ==>
ciudadrealeño, ña ==>
compostelano, na ==>
cordobés, sa ==>
coruñés, sa ==>
cuadragésimo, ma ==>
cuatrocientos, tas ==>
cuyo, ya ==>
tanto, ta ==>
tercero, ra ==>
terciario, ria ==>
tercio, cia ==>
tinerfeño, ña ==>
treceavo, va ==>
treintavo, va ==>
trescientos, tas ==>
trigésimo, ma ==>
tuyo, ya ==>

Son 113 de las 4105.

**Comment by jgsogo** [comment]
TODOs:

 * Revisar algunas reglas masculino/femenino que no están bien hechas.
 * Si una palabra ya está excluida, también debe estarlo su división.
