### ISSUE TITLE
Generar archivos de traducción

### ISSUE THREAD

**Issue by jgsogo** [jgsogo/neutron#22]
Hay que empezar a traducir. Hay varias subtareas:
1. Definir los idiomas (en principio los mismos que regiones)
2. Verificar que todos las cadenas están marcadas como traducibles
3. Implementar el cambio de idioma y localización inicial basada en la configuración del navegador.

**Comment by jgsogo** [comment]
Archivos de traducción generados para todas las regiones. Ahora toca sustituir las cadenas que sea preciso traducir (en caso de dejarla vacía, se utilizará la cadena correspondiente al español de España (es-ES).

La traducción se puede hacer cómodamente (y tediosa) a través de esta interfaz: http://ec2-52-40-137-175.us-west-2.compute.amazonaws.com/rosetta/. Hay que traducir tanto la pestaña _project_ como _third party_.

**Comment by mariavarelar** [comment]
He traducido la pestaña _project_, pero para _third party_, ¿no deberíamos esperar hasta que estén corregidos los textos de cada uno de los tres juegos?

**Comment by jgsogo** [comment]
Estoy totalmente de acuerdo en esperar, pero quería que vieras el "look and feel". Es un trabajo ímprobo traducir a todas las variantes, pero no se me ocurre otra forma de hacerlo :sob: (aunque probablemente a las variantes sólo haya que traducir cosas muy concretas, ¿no?)

**Comment by mariavarelar** [comment]
Bueno, por defecto aparecerá el español de España y no el inglés, ¿verdad? Entonces no me preocupa mucho, en una segunda vuelta neutralizo y con algo de tiempo y lo que aprendamos con el proyecto, vamos afinando.

**Comment by jgsogo** [comment]
En teoría sí. El idioma que aparece depende de la configuración del navegador con el que acceda cada usuario (aunque se puede forzar, por ejemplo, a que en el caso de los informantes aparezca su idioma).

Por resumir el orden de aparición de idioma sería el siguiente:

1. ¿Idioma del informante o idioma del navegador? <== **Tenemos que definir cuál queremos**
2. Si no existe el idioma anterior (imaginemos que era español-bolivia), aparecería el idioma "general" si existe (en el ejemplo anterior, el idioma "general" de español-bolivia es español).
3. Si no existe el anterior, aparecería el idioma por defecto (español)
4. Si no existe el idioma por defecto, aparecería el texto que está en el código fuente.

**Comment by mariavarelar** [comment]
Ok. En 1 podemos poner la variedad del informante, es más molón ;-)

**Comment by jgsogo** [comment]
Abro el ticket #29 para anotarme esto. Este issue lo dejamos para cosas relacionadas con la traducción en sí: que no aparezca, cadenas mal traducidas,...
