### ISSUE TITLE
Juego 3 (palabras groseras): necesitamos un botón para deshacer

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#24]
Como el juego 3 es muy rápido, la mano va más deprisa que el cerebro, necesitamos un botón que permita volver atrás y corregir.

**Comment by jgsogo** [comment]
**¿Seguro que lo queremos poner?** ¿Y deshacer cuántos pasos? ¿Sólo la última?

**Comment by mariavarelar** [comment]
Podemos hacer algo intermedio y permitir deshacer solo la última, ¿no te parece? Es que, aunque el informante esté atento y sea un tipo majete y cumplidor, la inercia de pulsar "no grosera" es fortísima.

**Comment by jgsogo** [comment]
Te prometo que cuando me pongo a hacerlo y le doy vueltas no me parece para nada natural el botón de "deshacer"... échale una pensada y trata de imaginar lo que ve el informante en cada uno de los pasos, ¿te parece claro?

**Comment by mariavarelar** [comment]
¿Lo que te preocupa es la confusión del informante al ver un botón de deshacer? Eso lo entiendo, no es lo más limpio, ¿pero no ves un riesgo grande en la inercia de contestar "no grosera"? ¿Un botón que diga "retroceder", colocado arriba a la derecha, te parece un despropósito?
