### ISSUE TITLE
Juego 2 (alternativa): ¿podemos añadir ejemplos?

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#26]
Como en el juego 1, sería bueno añadir ejemplos en el juego 2. En el caso que copio se aprecia cómo facilitaría el trabajo de los informantes:

![image](https://cloud.githubusercontent.com/assets/16288726/17208376/ca9510c2-54b8-11e6-8e67-1105456367e1.png)

Ejemplo: _El primer ciclista sacó varios minutos de ventaja al segundo clasificado._

**Comment by jgsogo** [comment]
Ahora que hemos añadido la coletilla _"En <location> se utiliza <word>"_ sí estoy de acuerdo; antes cuando no aparecía la palabra te lo hubiera discutido porque le estaríamos dando pistas... ;D
