### ISSUE TITLE
La página de consulta ha perdido el contenido original

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#35]
Al acceder a Consulta encuentro contenido de la página de registro:
![image](https://cloud.githubusercontent.com/assets/16288726/18199260/cbfa6260-70ff-11e6-8377-3ba1677acb1c.png)
¿Podemos recuperar la versión anterior de esta página?

**Comment by jgsogo** [comment]
Sin aceptar el código ético no te dejaría consultar palabras, por eso te aparece eso. Una vez que lo aceptes ya te aparece lo que buscas...
