### ISSUE TITLE
Orden de los juegos 1, 2 y 3 en el menú

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#36]
Esto... ¿podemos ordenar los juegos en el menú?

![image](https://cloud.githubusercontent.com/assets/16288726/18199379/44fdfdac-7100-11e6-9405-0c3505459e64.png)

:D :D :D

**Comment by jgsogo** [comment]
El tema es que los juegos se llaman "juego 1", "juego 2" y "juego 3" porque lo has traducido tú así. Los nombres originales son "word use", "word coarse", "word alternates". Me sorprendió ver esta traducción, ¿realmente queremos que aparezcan así o queremos darles un nombre de verdad?

**Comment by mariavarelar** [comment]
Es un nombre de verdad, a mí me gusta :) Recuerda a los usuarios que es un juego.

**Comment by jgsogo** [comment]
jajaja, ok. Lo que haré será escribirlos como "Game 1", "Game 2",... en el código y así encaja mejor la traducción.
