### ISSUE TITLE
Han sido eliminadas las palabras que solo se distinguen por un acento o la aparición de n/ñ

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#37]
Malas noticias :(

Al buscar en Words no he podido encontrar palabras como _sábana_, _revólver_, _mí_, _tú_, _mamá_ o _año_:

_Sábana_:

![image](https://cloud.githubusercontent.com/assets/16288726/18231835/5955fc9a-72c3-11e6-8171-37f99aa347d6.png)

_Año_:

![image](https://cloud.githubusercontent.com/assets/16288726/18231837/61354df8-72c3-11e6-8563-eac8182acd15.png)

Por cierto, puede ser un bonito momento para mejorar la herramienta de búsqueda y que, además de distinguir _n_ de _ñ_ y de ver los acentos haga búsquedas exactas ;-)

**Comment by jgsogo** [comment]
Me cagüen... ¡cómo no nos hemos dado cuenta de esto antes! Pues esto es un problema, sí, uno bastante gordo. Pienso una solución.

**Comment by jgsogo** [comment]
@mariavarelar,  confío en que ahora esté resuelto \o/
