### ISSUE TITLE
Al hacer logout, se muestra una página vacía

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#40]
![image](https://cloud.githubusercontent.com/assets/16288726/19838419/35afdfc6-9ecf-11e6-83d1-75217996d2a3.png)

Debería llevar a la home.

**Comment by jgsogo** [comment]
Se muestra ésta: https://github.com/jgsogo/neutron/blob/master/webapp/server/templates/users/logout.html

A mí me gustaría más algo especial incitando al usuario a volver, que dejarle en la "home" sin más... Cualquiera de los dos cambios es trivial.

**Comment by mariavarelar** [comment]
Podemos hacer algo intermedio y rapidito: replicamos la home pero colocamos arriba del todo (en un recuadro, quizá) un texto amable de este tipo:

"Gracias por el tiempo que has dedicado hoy a Neutrón, ¡vuelve pronto!".

Se podría hacer algo más chulo, como felicitar al informante por su progreso e incluir el porcentaje que ha avanzado o algo así, ¡pero quizá mejor poner los pies en el suelo!
