### ISSUE TITLE
El formulario de contacto no acusa recibo

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#41]
![image](https://cloud.githubusercontent.com/assets/16288726/19838436/7bb47f4a-9ecf-11e6-9e3b-6856e85111cd.png)

Debería aparecer al menos una página o un pop-up que diga: "¡Gracias por tu mensaje!, mantén tu e-mail vigilado, tendrás noticias nuestras".

**Comment by jgsogo** [comment]
Okidoki.

**Comment by jgsogo** [comment]
Pull request  #61 se encarga de esto: aparece un mensaje agradeciendo el envío y además se enviará copia de la pregunta.
