### ISSUE TITLE
En el formulario de contacto falta un campo de e-mail

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#42]
![image](https://cloud.githubusercontent.com/assets/16288726/19838469/28ed374c-9ed0-11e6-85e1-ce8af9137266.png)

Necesitamos una dirección de contacto. Añadir un campo que se llame "Dirección de correo electrónico".

**Comment by jgsogo** [comment]
Cierto es, hasta ahí pueden llegar usuarios sin registrar.
