### ISSUE TITLE
Se puede modificar el tamaño del campo para escribir el mensaje en el formulario de contacto

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#43]
En la esquina inferior derecha del campo para el mensaje hay un iconito que al pinchar y arrastrar permite deformar el campo. Esto es un poco raro :D
![image](https://cloud.githubusercontent.com/assets/16288726/19838489/9b84731a-9ed0-11e6-9b9c-28f411e1ffb5.png)

**Comment by jgsogo** [comment]
¿Te parece raro? En cualquier área de texto libre lo vas a encontrar... Prueba a escribir un buen párrafo ahí y dime cómo te sientes si te fuerzan a ver únicamente 2 líneas a la vez... o 3, o 10, o 500.

**Comment by mariavarelar** [comment]
No sé, creo que esperaba una barra de desplazamiento... Pero si a ti te encaja, no hay problema.

**Comment by jgsogo** [comment]
Las barras de desplazamiento pertenecen al pasado. Esto es el standard hoy en día, no creo que veas muchas barras en internet...
