### ISSUE TITLE
Formulario de registro: traducir "name"

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#46]
No he encontrado en Rosetta dónde traducir "name". Debería decir "Nombre y apellido".
![image](https://cloud.githubusercontent.com/assets/16288726/19838561/42af551e-9ed2-11e6-85a7-186b7a1e3909.png)

**Comment by jgsogo** [comment]
Aparece cuando se regeneren los archivos de traducción en 

rosetta > project > service > [Idioma]
