### ISSUE TITLE
Registro: error cuando cae la red durante el proceso

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#48]
Si durante el alta de un nuevo informante cae la red, el formulario se corrompe (un poquito).

![image](https://cloud.githubusercontent.com/assets/16288726/19838669/854e2164-9ed4-11e6-9d84-9625e9c72ed1.png)

**Comment by jgsogo** [comment]
"Se corrompe un poquito" quiere decir que aparece ese 11, ¿cierto? Me imagino que es el ID del país. Me lo apunto.

**Comment by mariavarelar** [comment]
Eso quiere decir, ¡gracias!
