### ISSUE TITLE
Registro pág. 2: es necesario editar el texto

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#49]
El texto de esta parte del formulario contiene muchas erratas y su estilo no nos pega. ¿Dónde lo puedo editar?
![image](https://cloud.githubusercontent.com/assets/16288726/19838687/b5276968-9ed4-11e6-8343-ca68c00dc003.png)

**Comment by jgsogo** [comment]
Pues lo "tradujiste" tú :laughing:  Está en

rosetta > project > España > Server > página 8/8

**Comment by mariavarelar** [comment]
No sé si me preocupa más haberlo traducido así o no ser capaz de verlo...

De verdad que no lo encuentro completo.

![image](https://cloud.githubusercontent.com/assets/16288726/19839039/7a634520-9edb-11e6-8467-70fc45347df5.png)

**Comment by jgsogo** [comment]
¿En serio?

![image](https://cloud.githubusercontent.com/assets/1406456/19839143/309df7da-9edd-11e6-946b-361fa767de22.png)

**Comment by jgsogo** [comment]
PR #60 updates tranlation strings.
