### ISSUE TITLE
Registro: es necesario que los informantes garanticen que cumplen los 3 requisitos

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#50]
El texto para solicitarlo está en Rosetta pero no lo he visto a lo largo del registro.

![image](https://cloud.githubusercontent.com/assets/16288726/19838716/52a59732-9ed5-11e6-9675-f80826a06c70.png)

**Comment by jgsogo** [comment]
Los tres requisitos aparecen enumerados en la página de "join" (cuando haces clic en "Únete").

**Comment by mariavarelar** [comment]
Pero necesitamos que nos digan que los cumplen.

**Comment by jgsogo** [comment]
¿Quieres un checkbox en cada uno de ellos? ¿No crees que es una acción adicional que le estamos pidiendo al usuario (una traba más para que se registre y participe) y que realmente no aporta nada que se pueda confirmar?

**Comment by mariavarelar** [comment]
Negociemos, si acepto que no incluyamos este check, ¿pones el del código ético?

**Comment by jgsogo** [comment]
Cada cosa por su lado.

Yo soy de la opinión de que cualquier clic/dato adicional en el registro provoca un _churn rate_ mínimo de un 20%. Y prefiero hacer estas preguntas después (vía mail/encuesta) que en el momento de registrarse.

**Comment by mariavarelar** [comment]
En esto me voy a enrocar. Puedo renunciar a datos sobre la edad o el sexo (esos sí los entiendo en una segunda vuelta, y así lo he visto hacer en otras plataformas), pero la única garantía que tenemos de que los datos que estamos recogiendo son relevantes es que los informantes afirmen que cumplen los requisitos. Es lo único a lo que podemos agarrarnos cuando presentemos las conclusiones de la investigación. No podemos decir "sí, hombre, los requisitos estaban por ahí arriba".
Así que dime a qué número de campos te parece que debemos limitar el formulario de registro y te marco los que no pueden faltar, ¿te parece bien?

**Comment by jgsogo** [comment]
No es una negociación, y mi función en esto se limita a hacer ver lo que creo.

**Comment by jgsogo** [comment]
Question: ¿y si no hacen el check en los tres? ¿No les dejamos registrarse?
