### ISSUE TITLE
Código ético: ¿dónde traduzco y completo?

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#51]
Al no aceptar el código ético, sale una pantalla con términos en inglés que no logro encontrar en Rosetta
![image](https://cloud.githubusercontent.com/assets/16288726/19838731/8be60338-9ed5-11e6-90a0-f8f67599d6d3.png)

**Comment by jgsogo** [comment]
Quedamos en no regenerar los archivos de traducción con cada cambio sino cuando hubiera algo más estable y duradero, ¿quieres que los regenere?

**Comment by mariavarelar** [comment]
¿Si los regeneras nos cargamos las traducciones que están en Rosetta? ¿Regenerarlos te lleva tiempo?

**Comment by jgsogo** [comment]
Regenerarlo es automático (acordarme de cómo se hace). En teoría sólo se eliminan las traducciones cuyo "inglés" original sera diferente y, si ha cambiado, pero son próximas, se marcan en un estado "revisar".
