### ISSUE TITLE
IMPORTANTE - Código ético: aceptación no obligatoria

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#52]
Ojo: es posible registrarse y participar sin aceptar el código ético.

**Comment by jgsogo** [comment]
El código ético da acceso a la búsqueda/consulta de lemas y significados, no a la participación.

**Comment by mariavarelar** [comment]
Sin aceptar el código no podemos permitir ni la participación ni la consulta de material de SM. Yo me cargaría la página de código ético y simplemente impediría que concluya el registro cualquiera que no haya marcado la casilla de código ético.

**Comment by jgsogo** [comment]
Relacionado con #35

**Comment by jgsogo** [comment]
Demasiado restrictivo desde mi punto de vista.

**Comment by mariavarelar** [comment]
¡Pero si no les cuesta nada! Es una petición muy razonable y no creo que nadie se vaya a llevar las manos a la cabeza por ella.
En todo caso, este es el tipo de cosa que podemos hablar con Antonio dentro de nada en esas cañas ;-)

**Comment by jgsogo** [comment]
Lo que se muestra sin la aceptación del código son trozos pequeños (definiciones individuales) del diccionario, que es precisamente la finalidad para la que nos lo han dejado. Ya se le muestra al usuario cuando se registra... y se lo podemos recordar de vez en cuando, pero de ahí a impedirle informar... preferiría que no fuera condición _sine qua non_.

**Comment by mariavarelar** [comment]
Me temo que sí es condición _sine qua non_ y, la verdad, no veo nada muy sorprendente en ella. Un día tendremos que presentar a SM el proyecto, y si no ven esa casilla nos la van a hacer poner (en el mejor de los casos).
Como te decía en el issue #50, para compensar podemos aligerar el formulario suprimiendo otros campos deseables pero no imprescindibles.

**Comment by jgsogo** [comment]
Sí consideras que es necesario de esa manera no vas a poder presentar ningún resultado a nadie (excepto a SM y en privado). No es lo que yo hubiera querido, pero una vez más, sólo opino, no es un negociación.
