### ISSUE TITLE
Juego 3: al hacer undo, ¿no deberíamos volver a la palabra sobre la que se ha hecho undo?

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#54]
Undo nos manda a la siguiente palabra, no a la anterior (translúcida). ¿Es correcto?

![image](https://cloud.githubusercontent.com/assets/16288726/19838819/59bb73aa-9ed7-11e6-94d2-49bec528c6c2.png)

**Comment by jgsogo** [comment]
Para mí es correcto. Así te obliga a fijarte más la próxima vez.

**Comment by mariavarelar** [comment]
Perfecto.

**Comment by jgsogo** [comment]
(pues cierra) ^^

**Comment by mariavarelar** [comment]
Ah, ¿que a ti no te gusta el trabajo infinito?
