### ISSUE TITLE
La sección worduse (juego 1) de Rosetta está incompleta

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#56]
Para este juego Rosetta solo ofrece una frase (que no sé bien por qué está aquí). Parece que el contenido que realmente corresponde al juego está repartido por otras secciones. No es muy importante, pero igual en el futuro nos complica las actualizaciones...

![image](https://cloud.githubusercontent.com/assets/16288726/19838903/e908992e-9ed8-11e6-8082-ac33429e8450.png)

**Comment by jgsogo** [comment]
Opción:

1. Si te refieres a los textos de los botones, éstos están asociados al enumerado ([aquí](https://github.com/jgsogo/neutron/blob/master/webapp/neutron/models/data.py#L57)). Cierre entonces el issue.
2. Si te refieres a otra cosa, voy a necesitar que te expliques un poco más.

**Comment by mariavarelar** [comment]
Para el juego 2 voy a Rosetta y todo lo que veo en la interfaz lo tengo listo para traducir:

![image](https://cloud.githubusercontent.com/assets/16288726/19839472/e9a28e58-9ee2-11e6-82f6-24f72458910b.png)

Para el juego 1 voy a Rosetta y solo tengo encuentro una frase que en realidad no corresponde a este juego. ¿hago la traducción directamente en el código, donde me indicas? ¡Lo que mandes!

**Comment by jgsogo** [comment]
No, no, no, el código no lo toques... :scream: :scream: Las cadenas de texto que aparecen en el código con `_("texto")` son las que se llevan a rosetta para traducir, así que ahí no hace falta tocar nada.

Pueden estar ocurriendo varias cosas:
 * quizá ahora tampoco salieran tantos textos en wordalternate si volviéramos a regenerar los archivos.
 * si dos textos son idénticos, sólo aparecen una vez por aplicación (la frase "There are no meanings in the database" aparece en varios juegos).
 * que realmente no haya nada más que traducir: si navegas por el código que hay en la carpeta correspondiente a este juego (https://github.com/jgsogo/neutron/tree/219c7f97c0c508740e547e09533421aec65769d1/webapp/question/worduse) podrás ver que la única cadena que está marcada para traducir con `_("blablabla")` o con `{% trans "blablabla" %}` es la que te aparece en rosetta. No hay más.

**Comment by mariavarelar** [comment]
Me estoy perdiendo un poquillo y no quiero darte la lata con esto. Lo que necesito es:

- Saber si se van a perder las traducciones que he hecho en Rosetta (para copiármelas en alguna parte antes de que eso ocurra).
- Que cuando llegue el momento me guíes para localizar los textos que veo en inglés en la plataforma y con los que no haya podido dar en Rosetta. Si es que esto sigue ocurriendo.
- Que planifiquemos esa regeneración de los archivos de traducción.

**Comment by jgsogo** [comment]
Resumiendo:
 * No se pierden las traducciones.
 * La aplicación "rosetta" te indica el pordentaje de líneas que han sido traducidas, las cadenas que han cambiado, te permite filtrar... si hay textos que no aparecen es porque no están marcados para traducir en el código.
 * Cuando suba una nueva versión, se regenerarán los archivos (me gustaría que fuera este fin de semana).
