### ISSUE TITLE
Error al guardar cambios en una acepción

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#58]
No puedo guardar cambios en las definiciones. Al hacer clic en guardar dentro de Inicio › Neutrón › Meanings › aparece un mensaje de error.

Normalmente no trabajo en este panel sino en el de Words (Inicio › Neutrón › Words), pero a veces necesito trabajar por acepciones en lugar de por entradas completas. Por ejemplo:
- Para corregir definiciones que generan bucles, como esta:

![image](https://cloud.githubusercontent.com/assets/16288726/19839323/ee65149a-9edf-11e6-9722-01dd497de215.png)
- Para seleccionar acepciones (no lemas completos) que deben omitirse en los juegos 1 y 3. Por ejemplo, no necesitamos presentar a los informantes "neón" (elemento de la tabla periódica) ni "siete" (numero) salvo cuando significan "lámpara" y "roto".

Por cierto, en el panel Words el texto que acompaña al check para omitir lemas dice "If set, this word won't be shown to informers in WordCoarse interface". Siempre he supuesto que ese texto estaba obsoleto y que el lema se omitirá tanto en el juego 1 como en el 3, es cierto, ¿verdad? Glups.

**Comment by jgsogo** [comment]
¿Debemos editar el diccionario de SM? Mi respuesta sería no, es la información que ha aportado SM y yo no la tocaría... prefiero marcar esta definición para que no se muestre y crear una nueva que estará asignada al informante "María" (España).

Igualmente, tenemos abierta la posibilidad de modificar las palabras, pero es algo que me produce pesadillas. Creo que deberían ser inmodificables, aún cuando tengan errores ortográficos o sea evidente que el informante se ha equivocado al escribirlo.

Dicho lo anterior: no se justifica que dé un error (que lo da), pero soy más de la opinión de prohibir estas modificaciones. <-- Decidamos esto antes de actuar.

-----

Nope, el texto es correcto, sólo se eliminan del juego "WordCoarse", en el juego "WordUse" se eliminan por significado (no por palabra).

**Comment by mariavarelar** [comment]
Entiendo la reticencia, pero sí vamos a tener que tocar el diccionario si queremos hacer un buen trabajo. Es más, yo ya he tocado donde me ha dejado Neutrón. Es una intervención mínima, cuidadosa y, no te preocupes, con la bendición de las mejores prácticas editoriales ;-)

¿Por qué las pesadillas? Precisamente aquí puedes relajarte, Antonio, Elena y yo nos dedicamos a alterar publicaciones (un millón de veces las de SM) para mejorarlas y no se nos da del todo mal :D 

He revisado el contrato de confidencialidad y, como esperaba, no impide que hagamos modificaciones. Esto no significa que nos vayamos a volver locos. Solo es imprescindible resolver los errores que se general al presentar las acepciones de manera independiente (tengo localizados 113).

En cuanto a lo segundo, esto es muy mala noticia. Necesito que las exclusiones que voy haciendo en Words se apliquen a todos los juegos, no solo al 3. Es importante porque excluir entradas en Neutrón lleva mucho tiempo (por eso quería hacerlo en Excel, donde podría automatizar hasta cierto punto) y no es razonable hacer este trabajo dos veces. Como diría mi sobrina: haz una magia, porfa.

**Comment by jgsogo** [comment]
Modificar el diccionario que está en la base de datos (en vez de los archivos XML originales) provoca que ya nunca podamos recargar la base de datos si se produce algún problema. No hay trazabilidad, dejamos de saber qué se ha tocado y no podríamos reproducirlo. Pero tampoco es importante, sólo es necesario saberlo. **Corregiré el tema para que te deje modificar eso.**

-----

Entonces, que me aclare, si se marca una palabra para no mostrar, ¿se deben eliminar de los **todos los juegos** **todas sus acepciones**? Entonces, ¿deja de tener sentido marcar una acepción para que no se muestre? ¿O queremos que se puedan marcar acepciones individuales, y también palabras (todas sus acepciones)?
