### ISSUE TITLE
Criterio de eliminación de palabras/acepciones de los juegos

### ISSUE THREAD

**Issue by jgsogo** [jgsogo/neutron#59]
(from #58)

Entonces, que me aclare, si se marca una palabra para no mostrar, ¿se deben eliminar de los todos los juegos todas sus acepciones? Entonces, ¿deja de tener sentido marcar una acepción para que no se muestre? ¿O queremos que se puedan marcar acepciones individuales, y también palabras (todas sus acepciones)?

**Comment by mariavarelar** [comment]
Cuando marcamos una palabra para que no se muestre es que no queremos que se muestre en ninguno de los juegos. Una palabra como "no", "algún" o "catorce" la queremos fuera de nuestro glosario.
A veces no es posibles eliminar la palabra completa, solo algunas acepciones, como en "bajo" (prep.) vs "bajo" (estatura, instrumento). Las acepciones eliminadas no se mostrarán en el juego 1.
¿Mejor ahora?

**Comment by jgsogo** [comment]
Okidoki. Entonces mandan las palabras, y en segundo lugar las acepciones. Pero me quedan dudas:

 * ¿Esto funcionará bien con palabras como "bajo" que también significa "instrumento musical"?
 * ¿Qué pasa cuando un informante diga una palabra para cierta acepción, y esa palabra coincida con una que ha sido excluida? Entonces no se le mostrará a nadie nunca... cuando querríamos que otros informantes de esa zona la validaran.

**Comment by mariavarelar** [comment]
1. Esta pregunta me despista un poco. Lo que queremos es: si marcamos eliminar en una palabra, esa palabra se elimina en los tres juegos; si marcamos eliminar en una acepción, esa acepción queda eliminada en los juegos 1 y 2 (que son los únicos que muestran acepciones). La palabra en sí y las acepciones no eliminadas siguen jugando.
2. Es muy poco probable que esto ocurra, ¿podemos supervisar esos casos? (Por cierto, ¿esto significa que las palabras aportadas por los informantes se fusionan con las que ya están en el diccionario de SM? Por ejemplo, un mexicano usa "vitrina" en lugar de "escaparate", ¿sumaremos una acepción a la entrada original? ¿Me puedes contar cómo funciona?)

**Comment by jgsogo** [comment]
SM no es más que un informante, sus palabras/acepciones funcionan igual que las de cualquier otro, no hay diferencia a nivel de base de datos.

En el caso "vitrina" del mexicano que comentas, lo que ocurrirá será que aparecerá una nueva relación entre la palabra "virtrina" y la acepción "lugar en el que se exponen mercancías" informada por el informante X cuya región de origen es México. Igual que existía una relación entre "escaparate" y "lugar en el que se exponen mercancías" que había informado SM para la región España.

Visto lo anterior, lo que ocurre es que si "vitrina" es una palabra excluida nunca se verá asociada a ninguna acepción (ni en España, ni en México) en ningún juego. Y asimismo, si "lugar en el que se exponen mercancías" es un significado excluído, no se verá en los juegos junto a la palabra "vitrina" ni junto a "escaparate".

----

De momento lo vamos a dejar como tú dices. Pero esto me lleva a pensar que en el futuro la exclusión de palabras/acepciones debe realizarse asociada a una región.

**Comment by mariavarelar** [comment]
¿Cómo vamos con esto? Como influye en la traducción y en la limpieza del diccionario, cuando tengas alguna actualización dame un silbidito, porfa.
Por el momento el texto junto a las casillas para ocultar sigue distinguiendo entre juegos:
![image](https://cloud.githubusercontent.com/assets/16288726/20356385/a312ccc4-ac24-11e6-863e-1677423ce7cc.png)
![image](https://cloud.githubusercontent.com/assets/16288726/20356411/b2a90cde-ac24-11e6-8b10-ad8e7202b8ad.png)
