### ISSUE TITLE
Errores en el excel del diccionario

### ISSUE THREAD

**Issue by jgsogo** [jgsogo/neutron#6]
En el diccionario tenemos errores :/

p.ej.: bajo el epígrafe "abril" hay definiciones correspondientes a "abrir", ¿cómo vamos a tratar esto?

**Comment by mariavarelar** [comment]
Empiezo a limpiar errores esta misma tarde-noche. Podremos con ello ;-)

**Comment by jgsogo** [comment]
Entiendo que los archivos fuente actuales no contienen erratas.
