### ISSUE TITLE
Las páginas faq, join y home no se actualizan

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#63]
Hemos corregido el texto de varias páginas para actualizarlo, pero no veo los cambios al acceder a la web:

faq.html
join.html
home.html

En el caso de las faq, quedan pendientes las respuestas a dos preguntas, ya que están vinculadas con la solución que demos a dos issues.

**Comment by jgsogo** [comment]
¿Esas modificaciones que dices son los commits https://github.com/jgsogo/neutron/commit/538c7591e82aa55d11971d30a5d111b98678dbad y siguientes?

Eso se verá en la web cuando se actualice la versión que está en el servidor.

**Comment by mariavarelar** [comment]
¿Y cuándo se actualiza?

**Comment by jgsogo** [comment]
Como os comenté en el mail, espero hacerlo este fin de semana.
