### ISSUE TITLE
Traducción

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#68]
Como te decía por telegram, tengo algunos problemas para rematar la traducción. Es poco texto y parece muy sencillo, pero el orden en el que lo presenta Rosetta, la falta de contexto y el hecho de que no se actualiza sobre la marcha en la web no ayuda mucho :(
Fíjate en este pantallazo. Como en una primera aproximación traduje sin contexto, hay líneas que no tienen sentido:

![image](https://cloud.githubusercontent.com/assets/16288726/20354811/9e1ed73a-ac1f-11e6-9596-757db75444d1.png)

En este caso, tengo dudas, además, sobre lo que realmente queremos decir, así que este es mi mejor intento:

![image](https://cloud.githubusercontent.com/assets/16288726/20354874/c70ae562-ac1f-11e6-9b6a-4c731b5ccb33.png)

¿Puedes darme alguna pista sobre lo que va entre interrogaciones?

Como no parece muy práctico que te envíe pantallazos así de cada duda, ¿puede ser buena idea que pases tú primero por Rosetta, eches un vistazo a lo que está en blanco o marcado para revisión y pase yo después para editar y unificar?

**Comment by mariavarelar** [comment]
Te pongo un ejemplo.

Rosetta me ofrece "Coarse Words" y me ayuda con este enlace: models/data.py:45:

![image](https://cloud.githubusercontent.com/assets/16288726/20355481/c1e4ddca-ac21-11e6-8b24-da7083edf471.png)

No tengo forma de saber si debo traducir por "Juego 3", por "palabras groseras" o por alguna otra ingeniosidad. ¡Socorro!

**Comment by jgsogo** [comment]
Respecto a las cosas que comentas:

 * la interfaz de administración no es necesario traducirla, a fin de cuentas sólo la vamos a ver nosotros.

 * en el ejemplo que pones en la imagen, estoy de acuerdo en que ofrece poco contexto, 100%, es posible añadir comentarios, pero no lo he hecho, quizá en el futuro me acostumbre a hacerlo, pero creo que es como lo de comentar el código, una utopía. Dicho esto, te indico qué puedes hacer con ese `models/data.py:45`, puedes encontrarlo en:

   + `webapp/neutron/models/data.py` (línea 45), si te fijas basta con navegar por las carpetas del repositorio hasta ese archivo y te lleva al archivo de código fuente correspondiente...

   ...ahora bien, lo siguiente es saber qué significa ese pedazo de código 

![image](https://cloud.githubusercontent.com/assets/1406456/20368527/b54974e4-ac54-11e6-910c-d033b7d99c23.png)

    que en este caso es el nombre (traducido) del modelo. 

Mala solución tiene. Tengo que darle una vuelta a Rosetta para entender un poco mejor esta problemática.

**Comment by mariavarelar** [comment]
Me preocupa un poco no traducir la interfaz de administración... ¿y si los textos en inglés, después de las modificaciones que hemos hecho, han dejado de funcionar bien? Sé que no es muy grave, pero... qué pena dejarlo regular, ¿no?
Lo otro... ¡qué alivio que a ti también te parezca un marrón! Empezaba a pensar quno era cosa del riego XD

**Comment by mariavarelar** [comment]
He conseguido avanzar con la traducción del apartado que Rosetta agrupa como “Neutrón”, que es el que más guerra da. (Sip, es la interfaz de administración, pero realmente dejarla como está es una guarrería que solo entendemos nosotros dos, y si en algún momento hacemos un traspaso, nos fríen).

Como la web sigue sin actualizarse, he continuado a ciegas, pero yo creo que ya está casi a punto.

Si te pasas por Rosetta, verás que he marcado como vellosos (en serio, ¿vellosos? :D) algunos textos para que los revises y cerremos. Son poquitos, no te preocupes.

Uno de ellos tiene que ver con cómo se comportan las exclusiones (he traducido según lo que yo querría que hicieran) y otro con la sección Context. En el issue #70 puedes ver por qué dudo en el segundo.

En todo caso, cuando se actualice la traducción en la interfaz es posible que tenga que hacer algunos retoques. Por ejemplo, cuando utilizas “meaning” lo traduzco como “acepción”, lo mismo que para “definition”. Vamos a ver qué tal resulta.

**Comment by jgsogo** [comment]
Si no te gusta la traducción "vellosos" (a mí tampoco) la tienes [aquí](https://github.com/mbi/django-rosetta/blob/develop/rosetta/locale/es/LC_MESSAGES/django.po) y puedes abrirles un issue y sugerir otra.

---

Respecto a la actualización de la interfaz, tu usuario está en "Argentina" y me imagino que estás modificando las traducciones de es_ES, ¿no? Quizá por eso no las veas reflejadas.

---

**Comment by mariavarelar** [comment]
Nah, era hablar por hablar.
------
¡Pero había entendido que el español de España mandaba y que cancelábamos las demás localizaciones hasta nueva orden!

**Comment by jgsogo** [comment]
A la hora de seleccionar el idioma de la interfaz manda el español de España (`es_ES`) sobre el idioma por defecto (inglés), pero si el usuario tiene otro configurado mandará el usuario siempre (primero lo que tenga definido en Neutrón y luego lo tenga en su navegador).

Respecto a la disponibilidad de las traducciones, manda el español `es`, pero el español de España `es_ES` y el español de argentina `es_Ar` están al mismo nivel.

**Comment by mariavarelar** [comment]
Es que no necesitamos un español de España y uno de Argentina. Ni lo necesitamos ni podemos asumir ese trabajo. Estoy neutralizando todo lo que puedo al traducir para que el texto encaje lo mejor posible en todas partes. El español de España es en realidad español neutro, y sí debe estar por encima de los demás.
_______
No dices nada sobre revisar esas traducciones problemáticas, ¿puedes echarles un vistazo?

**Comment by jgsogo** [comment]
Por favor, ¿ejemplo de traducción problemática? Vamos mezclando ideas en el mismo hilo y soy incapaz de seguirlo.

**Comment by mariavarelar** [comment]
¡Que no cunda el pánico! :D 

Te copio de arriba;

_Si te pasas por Rosetta, verás que he marcado como vellosos (en serio, ¿vellosos? :D) algunos textos para que los revises y cerremos. Son poquitos, no te preocupes._

_Uno de ellos tiene que ver con cómo se comportan las exclusiones (he traducido según lo que yo querría que hicieran) y otro con la sección Context. En el issue #70 puedes ver por qué dudo en el segundo._

Así que... Esas son las traducciones problemáticas: los vellosos de Rosetta para el español de España, sección Neutrón.

¿Mejor ahora?

**Comment by jgsogo** [comment]
Ok, traducidos, échales un ojo. Eso sí, como te he comentado por mensaje, me gustaría conservar traducciones evidentes para los nombres de los juegos "WordUse", "WordAlternate" y "WordCoarse", así en las interfaces de admnistración se sabe claramente a qué hace referencia cada uno.

**Comment by jgsogo** [comment]
He estado mirando esto y creo que no es tanto lío... pero hace falta ponerse el gorro de "estoy construyendo algo y requiere trabajo y atención". Respecto a la traducción de `Word alternate`, por poner un ejemplo, que es exactamente el mismo texto y aparece en dos sitios:

1. como título del juego correspondiente, y que quieres traducir por "Juego 2". Esta cadena aparece en la plantilla correspondiente ([aquí](https://github.com/jgsogo/neutron/blob/master/webapp/question/wordalternate/templates/wordalternate/home.html#L5)) y en la interfaz de Rosetta aparece entrando por `[idioma] > WordAlternate >`

![image](https://cloud.githubusercontent.com/assets/1406456/20866194/1af81680-ba27-11e6-96e2-12ccc21681ed.png)


2. como título del modelo de datos ([aquí](https://github.com/jgsogo/neutron/blob/master/webapp/neutron/models/data.py#L83)) y que deberíamos traducir como "Palabra alternativa".

![image](https://cloud.githubusercontent.com/assets/1406456/20866197/4687e62c-ba27-11e6-9575-7681b2ccea35.png)

Y esto funciona.

**Comment by jgsogo** [comment]
Sin embargo, efectivamente, para que funcione bien hay que ponerle contexto: https://docs.djangoproject.com/en/dev/topics/i18n/translation/#contextual-markers

**Comment by jgsogo** [comment]
Ok, solucionado (el caso de `Word alternate`); sin embargo, para que se refresquen las traducciones sólo hay dos opciones:

1. lo ejecutas en local.
2. avisas y reinicio el servidor

**Comment by mariavarelar** [comment]
Puedes reiniciar cuando quieras.
