### ISSUE TITLE
Identificar definiciones que no queremos mostrar a los informantes

### ISSUE THREAD

**Issue by jgsogo** [jgsogo/neutron#7]
Algunas definiciones no convendría mostrarlas a los informantes; cosas como "épico, ca: mirar épica" no aportan nada... lo ideal sería identificarlas y poder decidir qué hacer con ellas.

**Comment by mariavarelar** [comment]
Voy a identificar esos casos y a añadir la entrada a la que deberían remitir.

**Comment by jgsogo** [comment]
Si quieres podemos mirar un ejemplo antes de hacerlo con todos los casos para tener la seguridad de que se puede programar luego con facilidad.

El script que importa el excel es [éste](https://github.com/jgsogo/neutron/blob/master/webapp/words/management/commands/import_tsv.py), primero lo exporto a texto plano separado por tabuladores y luego voy leyendo línea a línea.

¿Cómo tienes pensado marcar estos casos?

**Comment by mariavarelar** [comment]
Claro que sí.

"antidoping", por ejemplo, remite a "antidopaje". Lo que yo haría es ir a la celda donde pone "antidopaje" y escribir "antidopaje o antidoping", después:

a) eliminaría la fila de "antidoping" o
b) conservaría esa fila y escribiría "&" en el espacio correspondiente a su definición.

(Es verdad que México puede preferir "antidoping" y España "antidopaje", pero en algún sitio tenemos que cortar, ¿no crees?).

Creo que a) facilita la programación y b) es más conservador. Como estés más cómodo.

El script se ve tan limpio que hasta voy a intentar aprender ;-)

**Comment by jgsogo** [comment]
Yo no sería tan agresivo con los datos que ya tenemos. ¿Qué te parece lo siguiente? Añadir una columna a todas las filas y escribir en ella la palabra alternativa que debe mostrarse, algo como:

Palabra | Alternativa | Definiciones
-----------|----------------|-----------------
antidoping | antidopaje | bla, bla, bla, definiciones que ya estén
antidopaje |  |  las definiciones

Así mantenemos toda la información y podemos identificar las palabras que no queremos mostrar

___

De todas formas hay otro problema, ¿y si sólo queremos redirigir algunas definiciones? Podríamos hacer algo como lo siguiente:

Palabra | Def#1 | Def#2 | Def#3 | ....
-----------|----------|---------|----------|------
abajo | 1.En un lugar o en una posición inferiores | 2.Hacia un lugar | 3.Y más definiciones
abajo2 | 1.Definición que nos vale | 2[otra palabra].Definición que no gusta

Con algo así podríamos seguir mostrando la ```def#1``` de la palabra ```abajo2```, mientras que no lo haríamos para la ```def#2``` (y además tenemos información adicional q podríamos utilizar en el futuro)... o simplemente dejando los corchetes vacíos si sólo queremos eliminarla.

¿Opiniones?

**Comment by mariavarelar** [comment]
Podemos hacer eso, claro que sí.

Parece que hay unos 50 casos con la referencia "Mira en", esos los trato como dices. Me refería a los otros 200 en los que hay un problema de doble grafía (bacón, bacon).

Lo que es muy importante desde mi punto de vista es recordar que no estamos recopilando información sobre preferencias ortográficas, sino sobre preferencias léxicas. Es que el ejemplo del antidopaje no era muy bueno. Los informantes deben ver a la vez "hierbabuena" y "yerbabuena" y saber que no nos preocupa si prefieren con h o con y. Nos interesa la lengua, no la escritura.

Por eso quería dároslo ya fusionado en una sola entrada, para evitar que nos salgamos del alcance y despistemos a los informantes.

¿Me pongo muy cabezota con esto? Jajaja, si alguien está deseando que hagamos un proyecto sobre ortografía, tengo un glosario genial para eso ;-)

**Comment by jgsogo** [comment]
Ok, genial. La verdad es que yo no estaba pensando en esas diferencias de
grafía. En esos casos sí que se puede poner como dices.

Seguimos.

*Javier García Sogo*
Senior Software Engineer, Climber, Data Scientist
Twitter <https://twitter.com/jgsogo> | GitHub <https://github.com/jgsogo> |
LinkedIn <https://www.linkedin.com/in/jgsogo>

**Comment by jgsogo** [comment]
La interfaz de administración permite marcar:
 * las palabras que no queremos mostrar en "Word coarse"
 * las palabras-definición que no queremos mostrar en "WordUse" ni "WordAlternate"

**Comment by jgsogo** [comment]
@mariavarelar ¿es suficiente con las posibilidades que ofrece la interfaz de administración? ¿Podemos cerrar esto?

**Comment by jgsogo** [comment]
Hablamos de que valía, cierro.
