### ISSUE TITLE
Traducción juegos

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#71]
Mira, este caso es genial.
Pantallazo de la traducción:

![image](https://cloud.githubusercontent.com/assets/16288726/20387153/10787616-acbf-11e6-8d58-9924f2752242.png)

Pantallazo de la interfaz:

![image](https://cloud.githubusercontent.com/assets/16288726/20387239/76171608-acbf-11e6-9df8-a85c711e8894.png)

(Inciso: ¿podemos eliminar la línea que dice "value"?)

Y fíjate que algunas traducciones han subido, pero unas sí, otras no (el juego 1, por ejemplo, no), incluso he visto vacilaciones como esta (dos ventanas de incógnito, la que está mal, curiosamente, la abrí unos segundos después de la que está bien):

![image](https://cloud.githubusercontent.com/assets/16288726/20387562/fb145ae0-acc0-11e6-87f9-0f19e8354e37.png)

¿Ves lo que tengo que sufrir? XD

**Comment by jgsogo** [comment]
Lo primero, cuando dos cadenas iguales se traducen de distintas formas no tengo claro cuál de ellas coge (lo miraré); fíjate que ayer mismo me pasaste un pantallazo donde "Word alternate" lo traducías como "significante alternativo".

----

Respeto a lo segundo con las ventanas de incógnito, ¿en qué idioma estaba configurada cada una de esas ventanas?

----

Please, las pruebas, con toda la información posible, y sólo un asunto por issue. ;D

**Comment by mariavarelar** [comment]
Sí, entiendo por qué ocurre, pero eso no significa que podamos traducir esas cadenas siempre de la misma manera. La traducción al inglés hizo que se perdieran matices del español, y es importante que los recuperemos. En ello estoy, ¿puedes hacer que funcione?
_________
En español. Mismo equipo (HP Envy 17 Notebook PC), mismo navegador (Chrome perfectamente actualizado), misma hora (11:32), mismas condiciones atmosféricas (11 grados, lluvia).
________

Ok (aunque no sé qué es lo que echas en falta, la verdad) y... haré lo que pueda, pero qué aburrido.

**Comment by jgsogo** [comment]
Quiero creer que se selecciona la traducción adecuada al lugar en el que se pone. Si no es así habrá que cambiar las cadenas originales en inglés para que sean unívocas. Si no es posible, no voy a cambiar cómo funciona la internacionalización y localización en Django, está por encima de mis posibilidades; pero a lo mejor hay algo en la documentación que habla de esto y se me ha escapado ([link](https://docs.djangoproject.com/es/1.9/topics/i18n/))
---
Yo pruebo, y por más que le doy al F5 siempre me sale lo mismo...

**Comment by mariavarelar** [comment]
Yo también quiero creer eso, glups. Mañana accedo con un usuario de España y la mente clara, me armo de paciencia y te cuento si detecto errores.

**Comment by jgsogo** [comment]
entiendo que si en 16 días no se ha actualizado un "mañana accedo [...] y te cuento si detecto errores" es que se puede cerrar.

**Comment by mariavarelar** [comment]
Hemos hablado de esto por telegram y, como te dije, te enviaré un documento con las traducciones que no funcionan (lo que veo en la interfaz y lo que debería ver, tanto para usuarios españoles como para americanos), con independencia de cuál sea el origen del error.
