### ISSUE TITLE
Idea/Funcionalidad: Menú "participa" para administradores

### ISSUE THREAD

**Issue by mariavarelar** [jgsogo/neutron#9]
Para usuarios con permisos de administrador sería bueno contar con un cuarto tipo de contribución, la que nos permite marcar lemas que sabemos positivamente que son español neutro y con los que, como dijo Antonio, "no podemos marear a los usuarios".

![image](https://cloud.githubusercontent.com/assets/16288726/16199110/a8fb8e3c-3708-11e6-9805-d98055d176de.png)

Planteamos esta idea por mail el 9 de junio.

**Comment by jgsogo** [comment]
@mariavarelar, esto se puede hacer en la interfaz de administración, tal y como contaba en el mail.
